"""migration message

Revision ID: b874806f087c
Revises: 
Create Date: 2025-12-23 23:35:57.350815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b874806f087c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(), nullable=False, comment='Company name'),
    sa.Column('slug', sa.String(), nullable=False, comment="URL-friendly identifier (e.g., 'acme-corp')"),
    sa.Column('company_id', sa.String(), nullable=False, comment='Company ID for Auth0 organization mapping'),
    sa.Column('shopify_store_url', sa.String(), nullable=False, comment="Shopify store URL (e.g., 'https://my-store.myshopify.com')"),
    sa.Column('shopify_access_token', sa.String(), nullable=False, comment='Shopify Admin API access token (should be encrypted in production)'),
    sa.Column('shopify_api_version', sa.String(), nullable=False, comment="Shopify API version (e.g., '2024-01')"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is tenant active'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='Additional tenant-specific settings (JSON)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_company_id'), 'tenants', ['company_id'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('orders',
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant (company) this order belongs to'),
    sa.Column('shopify_draft_order_id', sa.String(), nullable=False, comment='Shopify draft order ID (gid://shopify/DraftOrder/...)'),
    sa.Column('shopify_order_id', sa.String(), nullable=True, comment='Shopify order ID after completion (gid://shopify/Order/...)'),
    sa.Column('customer_email', sa.String(), nullable=False, comment='Customer email address'),
    sa.Column('customer_name', sa.String(), nullable=True, comment='Customer full name'),
    sa.Column('total_price', sa.Float(), nullable=False, comment='Total order price'),
    sa.Column('currency', sa.String(), nullable=False, comment='Currency code (USD, EUR, etc.)'),
    sa.Column('line_items', sa.JSON(), nullable=True, comment='Order line items (products) as JSON'),
    sa.Column('validado', sa.Boolean(), nullable=False, comment='Whether payment has been validated'),
    sa.Column('validated_at', sa.DateTime(), nullable=True, comment='Timestamp when payment was validated'),
    sa.Column('payment_method', sa.String(), nullable=True, comment='Payment method used'),
    sa.Column('notes', sa.String(), nullable=True, comment='Additional notes about the order'),
    sa.Column('status', sa.String(), nullable=False, comment='Order status (draft, completed, failed, cancelled)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'shopify_draft_order_id', name='uq_tenant_draft_order')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_shopify_draft_order_id'), 'orders', ['shopify_draft_order_id'], unique=False)
    op.create_index(op.f('ix_orders_shopify_order_id'), 'orders', ['shopify_order_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_orders_validado'), 'orders', ['validado'], unique=False)
    op.create_table('users',
    sa.Column('auth0_user_id', sa.String(), nullable=False, comment='Auth0 user ID (sub claim from JWT)'),
    sa.Column('email', sa.String(), nullable=False, comment='User email address'),
    sa.Column('name', sa.String(), nullable=True, comment='User full name'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant (company) this user belongs to'),
    sa.Column('role', sa.Enum('ADMIN', 'LOGISTICA', 'VENTAS', 'VIEWER', name='role'), nullable=False, comment='User role (ADMIN, LOGISTICA, VENTAS, VIEWER)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is user active'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='Last login timestamp'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth0_user_id'), 'users', ['auth0_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_orders_validado'), table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_shopify_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_shopify_draft_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_company_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
