"""add_is_platform_and_encrypt_shopify_token

Revision ID: 5bc42defbfa9
Revises: d766a87077f2
Create Date: 2025-12-29 15:35:58.101869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc42defbfa9'
down_revision: Union[str, None] = 'd766a87077f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_platform', sa.Boolean(), nullable=False, server_default='false', comment='True if this is the VentIA platform tenant (not a client)'))
    op.add_column('tenants', sa.Column('_shopify_access_token_encrypted', sa.String(), nullable=True, comment='Encrypted Shopify Admin API access token (use shopify_access_token property)'))
    op.drop_column('tenants', 'shopify_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('shopify_access_token', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Shopify Admin API access token (should be encrypted in production)'))
    op.drop_column('tenants', '_shopify_access_token_encrypted')
    op.drop_column('tenants', 'is_platform')
    # ### end Alembic commands ###
