"""Add delivery fields to orders

Revision ID: add_delivery_fields
Revises: 4bc433f2dd5c
Create Date: 2025-12-27 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_delivery_fields'
down_revision: Union[str, None] = '4bc433f2dd5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('expected_delivery_date', sa.DateTime(), nullable=True, comment='Expected delivery date of the order'))
    op.add_column('orders', sa.Column('dispatch_time_window', sa.String(), nullable=True, comment="Dispatch time window (e.g., '09:00-12:00')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'dispatch_time_window')
    op.drop_column('orders', 'expected_delivery_date')
    # ### end Alembic commands ###
