"""migration message

Revision ID: 4bc433f2dd5c
Revises: b874806f087c
Create Date: 2025-12-24 12:26:13.785649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc433f2dd5c'
down_revision: Union[str, None] = 'b874806f087c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Company ID for Auth0 organization mapping')
    op.alter_column('tenants', 'shopify_store_url',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment="Shopify store URL (e.g., 'https://my-store.myshopify.com')")
    op.alter_column('tenants', 'shopify_access_token',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Shopify Admin API access token (should be encrypted in production)')
    op.alter_column('tenants', 'shopify_api_version',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment="Shopify API version (e.g., '2024-01')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'shopify_api_version',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment="Shopify API version (e.g., '2024-01')")
    op.alter_column('tenants', 'shopify_access_token',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Shopify Admin API access token (should be encrypted in production)')
    op.alter_column('tenants', 'shopify_store_url',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment="Shopify store URL (e.g., 'https://my-store.myshopify.com')")
    op.alter_column('tenants', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Company ID for Auth0 organization mapping')
    # ### end Alembic commands ###
