"""add_api_keys_table

Revision ID: 6b63927a59c5
Revises: add_delivery_fields
Create Date: 2025-12-29 10:36:49.464730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b63927a59c5'
down_revision: Union[str, None] = 'add_delivery_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('api_keys',
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='Hashed API key using bcrypt (never store plain text)'),
    sa.Column('key_prefix', sa.String(length=12), nullable=False, comment='First 12 characters of the key for identification'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Human-readable name for the API key (e.g., 'n8n-production')"),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant this API key belongs to'),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'LOGISTICA', 'VENTAS', 'VIEWER', name='role'), nullable=False, comment='Role associated with this API key (ADMIN, LOGISTICA, VENTAS, VIEWER)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the API key is active (can be revoked)'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Last time this API key was used'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Expiration date (optional, null means no expiration)'),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True, comment='User who created this API key'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name='uq_api_key_name_tenant')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=True)
    op.create_index(op.f('ix_api_keys_role'), 'api_keys', ['role'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_role'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
