"""add_api_keys_table

Revision ID: d766a87077f2
Revises: 6b63927a59c5
Create Date: 2025-12-29 10:44:19.388392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd766a87077f2'
down_revision: Union[str, None] = '6b63927a59c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               comment='Order status (Pagado, Pendiente, Enviado, Cancelado)',
               existing_comment='Order status (draft, completed, failed, cancelled)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               comment='Order status (draft, completed, failed, cancelled)',
               existing_comment='Order status (Pagado, Pendiente, Enviado, Cancelado)',
               existing_nullable=False)
    # ### end Alembic commands ###
