"""Add webhook_events table

Revision ID: e3c95ab8c78c
Revises: c0ef996c0615
Create Date: 2026-01-27 22:05:58.134495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c95ab8c78c'
down_revision: Union[str, None] = 'c0ef996c0615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
