"""add_channel_to_orders

Revision ID: 7fbd9b64d81b
Revises: 541e102dfed2
Create Date: 2026-02-07 14:32:25.365417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbd9b64d81b'
down_revision: Union[str, None] = '541e102dfed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('channel', sa.String(), nullable=True, comment='Sales channel: shopify, woocommerce, venta_whatsapp'))
    op.create_index(op.f('ix_orders_channel'), 'orders', ['channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_channel'), table_name='orders')
    op.drop_column('orders', 'channel')
    # ### end Alembic commands ###
