"""add structured shipping fields to orders

Revision ID: b050705fcc84
Revises: e1f71b23e005
Create Date: 2026-02-05 23:25:39.081761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b050705fcc84'
down_revision: Union[str, None] = 'e1f71b23e005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_city', sa.String(), nullable=True, comment='Shipping city'))
    op.add_column('orders', sa.Column('shipping_province', sa.String(), nullable=True, comment='Shipping province/state'))
    op.add_column('orders', sa.Column('shipping_country', sa.String(), nullable=True, comment="Country name (e.g., 'Peru', 'United States')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_province')
    op.drop_column('orders', 'shipping_city')
    # ### end Alembic commands ###
