"""add_shipping_address_to_orders

Revision ID: d9ed481f885b
Revises: 96fc34b43c44
Create Date: 2026-02-04 00:10:35.416886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ed481f885b'
down_revision: Union[str, None] = '96fc34b43c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=True, comment='Shipping address: address1, city'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###
