"""add_timezone_to_tenants

Revision ID: 541e102dfed2
Revises: b050705fcc84
Create Date: 2026-02-06 01:34:27.708633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541e102dfed2'
down_revision: Union[str, None] = 'b050705fcc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='America/Lima', comment="IANA timezone for this tenant (e.g., 'America/Lima', 'America/Bogota')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'timezone')
    # ### end Alembic commands ###
