"""add_n8n_reminder_workflow_id_to_tenants

Revision ID: da6b1eaa3f3e
Revises: 7fbd9b64d81b
Create Date: 2026-03-17 11:12:08.986087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6b1eaa3f3e'
down_revision: Union[str, None] = '7fbd9b64d81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('n8n_reminder_workflow_id', sa.String(length=50), nullable=True, comment='n8n workflow ID for temperature reminders'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'n8n_reminder_workflow_id')
    # ### end Alembic commands ###
