"""update webhook unique constraint to include event_type

Revision ID: 96fc34b43c44
Revises: 9f9398287434
Create Date: 2026-02-03 18:54:07.090248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fc34b43c44'
down_revision: Union[str, None] = '9f9398287434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_id_unique'), table_name='webhook_events')
    op.create_index('ix_webhook_event_id_unique', 'webhook_events', ['platform', 'event_id', 'event_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_event_id_unique', table_name='webhook_events')
    op.create_index(op.f('ix_webhook_event_id_unique'), 'webhook_events', ['platform', 'event_id'], unique=True)
    # ### end Alembic commands ###
