"""add_woocommerce_order_id_to_orders

Revision ID: 7f4a7df6fce6
Revises: c21ddad9b0cb
Create Date: 2026-01-21 10:59:36.403639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4a7df6fce6'
down_revision: Union[str, None] = 'c21ddad9b0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment='First 12 characters of the key (vnt_{uuid8}) for unique identification',
               existing_comment='First 12 characters of the key for identification',
               existing_nullable=False)
    op.add_column('orders', sa.Column('woocommerce_order_id', sa.Integer(), nullable=True, comment='WooCommerce order ID (integer)'))
    op.alter_column('orders', 'shopify_draft_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Shopify draft order ID (gid://shopify/DraftOrder/...)')
    op.create_index(op.f('ix_orders_woocommerce_order_id'), 'orders', ['woocommerce_order_id'], unique=False)
    op.create_unique_constraint('uq_tenant_woo_order', 'orders', ['tenant_id', 'woocommerce_order_id'])
    op.alter_column('tenants', 'efact_ruc',
               existing_type=sa.VARCHAR(length=11),
               comment='RUC del tenant para facturacion electronica',
               existing_comment='RUC del tenant para facturación electrónica',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'efact_ruc',
               existing_type=sa.VARCHAR(length=11),
               comment='RUC del tenant para facturación electrónica',
               existing_comment='RUC del tenant para facturacion electronica',
               existing_nullable=True)
    op.drop_constraint('uq_tenant_woo_order', 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_woocommerce_order_id'), table_name='orders')
    op.alter_column('orders', 'shopify_draft_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Shopify draft order ID (gid://shopify/DraftOrder/...)')
    op.drop_column('orders', 'woocommerce_order_id')
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment='First 12 characters of the key for identification',
               existing_comment='First 12 characters of the key (vnt_{uuid8}) for unique identification',
               existing_nullable=False)
    # ### end Alembic commands ###
