source 'https://rubygems.org'
ruby '3.4.4'

# Core Rails - API only
gem 'rails', '~> 7.2.2'
gem 'pg', '~> 1.5'
gem 'puma', '>= 6.4.3'

# Background jobs
gem 'sidekiq', '~> 7.3.0'
gem 'connection_pool', '~> 2.4'  # Fix compatibility with Sidekiq 7.3
gem 'redis', '~> 5.3'

# API & Serialization
gem 'rack-cors'
gem 'jbuilder'
gem 'active_model_serializers', '~> 0.10.0'

# WhatsApp & HTTP
gem 'twilio-ruby', '~> 7.3.3'
gem 'httparty'
gem 'faraday'

# State machines & Events
gem 'aasm', '~> 5.5'
gem 'wisper', '2.0.0'

# Notification settings bitmask (alternative to FlagShihTzu - using custom implementation)
# Bitmask flags are implemented manually in NotificationSetting model

# Utilities
gem 'kaminari'
gem 'email_reply_parser'
gem 'telephone_number'
gem 'valid_email2'
gem 'browser'

# Markdown & Templating
gem 'liquid', '~> 5.5.0'

# Image processing (for avatars)
gem 'image_processing', '~> 1.2'
gem 'aws-sdk-s3', require: false

# Monitoring
gem 'sentry-ruby'
gem 'sentry-rails'
gem 'sentry-sidekiq'

# Performance
gem 'bootsnap', require: false

# API Documentation (Swagger/OpenAPI)
gem 'rswag-api'
gem 'rswag-ui'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails', '~> 7.0'
  gem 'rswag-specs'
  gem 'shoulda-matchers'
end

group :development do
  gem 'annotate'
  gem 'bullet'
  gem 'letter_opener'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'simplecov', require: false
  gem 'webmock'
  gem 'vcr'
end
